name: Build

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: Build package
        run: |
          uv build
          
      - name: Test package installation
        run: |
          # Create a clean environment and test installation
          uv venv test-env
          source test-env/bin/activate
          uv pip install dist/*.whl
          python -c "from opensearch_logger.version import __version__; print(f'Package version: {__version__}')"
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 30
