name: Lint

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    name: Format and Lint
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: Install dependencies
        run: |
          uv sync --all-extras
          
      - name: Check formatting
        run: |
          uv run ruff format --check .
          
      - name: Check linting
        run: |
          uv run ruff check .
          
      - name: Type checking
        run: |
          uv run mypy opensearch_logger --strict
